import { defineConfig } from 'vitepress';

// yondermesh docs site config.
// Source of truth: repo root README.md / ARCHITECTURE.md / CONTRIBUTING.md + src/.
// Auto-generated pages (CLI reference, adapter matrix) live under reference/ and
// are regenerated by `npm run sync` from `scripts/docs/`. Never hand-edit those.

// Project Pages serve from https://<org>.github.io/yondermesh/, so base must be '/yondermesh/'.
// If the repo is ever renamed to <org>.github.io (user/org Pages root), set base back to '/'.
const base = '/yondermesh/';

export default defineConfig({
  lang: 'en-US',
  title: 'yondermesh',
  description: 'Self-hosted Agent Context Bus — let your AI agents see each other, query each other, and hand off tasks across devices and CLIs.',
  base,
  lastUpdated: true,
  cleanUrls: true,
  head: [
    ['meta', { name: 'theme-color', content: '#0ea5e9' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: 'yondermesh' }],
    ['meta', { property: 'og:description', content: 'Self-hosted Agent Context Bus — let your AI agents see each other, query each other, and hand off tasks across devices and CLIs.' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
  ],
  locales: {
    root: {
      label: 'English',
      lang: 'en',
      themeConfig: {
        nav: navEn(),
        sidebar: sidebarEn(),
        editLink: {
          pattern: 'https://github.com/GoYonderTogether/yondermesh/edit/main/site/:path',
          text: 'Edit this page on GitHub',
        },
        footer: {
          message: 'Released under the MIT License.',
          copyright: 'Copyright © 2025-present 未至之境 (GoYonderTogether)',
        },
      },
    },
    zh: {
      label: '简体中文',
      lang: 'zh-CN',
      themeConfig: {
        nav: navZh(),
        sidebar: sidebarZh(),
        editLink: {
          pattern: 'https://github.com/GoYonderTogether/yondermesh/edit/main/site/:path',
          text: '在 GitHub 上编辑此页',
        },
        footer: {
          message: '基于 MIT 协议发布。',
          copyright: 'Copyright © 2025-present 未至之境 (GoYonderTogether)',
        },
      },
    },
  },
  themeConfig: {
    socialLinks: [
      { icon: 'github', link: 'https://github.com/GoYonderTogether/yondermesh' },
    ],
    search: {
      provider: 'local',
      options: {
        locales: {
          zh: { translations: { button: { buttonText: '搜索文档', buttonAriaLabel: '搜索文档' }, modal: { noResultsText: '无法找到相关结果', resetButtonTitle: '清除查询条件', footer: { selectText: '选择', navigateText: '切换', closeText: '关闭' } } } },
        },
      },
    },
    outline: { level: [2, 3], label: 'On this page' },
    docFooter: { prev: 'Previous', next: 'Next' },
    lastUpdatedText: 'Last updated',
    returnToTopLabel: 'Back to top',
    sidebarMenuLabel: 'Menu',
    darkModeSwitchLabel: 'Appearance',
  },
});

function navEn() {
  return [
    { text: 'Guide', link: '/guide/what-is-yondermesh', activeMatch: '/guide/' },
    { text: 'CLI', link: '/reference/cli', activeMatch: '/reference/' },
    { text: 'Adapters', link: '/reference/adapters', activeMatch: '/reference/adapters' },
    { text: 'GitHub', link: 'https://github.com/GoYonderTogether/yondermesh' },
  ];
}

function navZh() {
  return [
    { text: '指南', link: '/zh/guide/what-is-yondermesh', activeMatch: '/zh/guide/' },
    { text: 'CLI', link: '/zh/reference/cli', activeMatch: '/zh/reference/' },
    { text: '适配器', link: '/zh/reference/adapters', activeMatch: '/zh/reference/adapters' },
    { text: 'GitHub', link: 'https://github.com/GoYonderTogether/yondermesh' },
  ];
}

function sidebarEn() {
  return [
    {
      text: 'Introduction',
      collapsed: false,
      items: [
        { text: 'What is yondermesh?', link: '/guide/what-is-yondermesh' },
        { text: 'Quickstart', link: '/guide/quickstart' },
        { text: 'Installation', link: '/guide/installation' },
      ],
    },
    {
      text: 'Concepts',
      collapsed: false,
      items: [
        { text: 'Architecture', link: '/guide/architecture' },
        { text: 'Sessions & Topology', link: '/guide/sessions' },
        { text: 'Daemon', link: '/guide/daemon' },
        { text: 'Cross-device Sync', link: '/guide/sync' },
      ],
    },
    {
      text: 'Integrations',
      collapsed: false,
      items: [
        { text: 'MCP Server', link: '/guide/mcp' },
        { text: 'CLI Adapters', link: '/reference/adapters' },
        { text: 'Skills System', link: '/guide/skills' },
        { text: 'Mount System', link: '/guide/mount' },
      ],
    },
    {
      text: 'Reference',
      collapsed: false,
      items: [
        { text: 'CLI Commands', link: '/reference/cli' },
        { text: 'Configuration', link: '/reference/config' },
        { text: 'MCP Tools', link: '/reference/mcp-tools' },
        { text: 'File Layout', link: '/reference/files' },
      ],
    },
    {
      text: 'Project',
      collapsed: false,
      items: [
        { text: 'FAQ', link: '/guide/faq' },
        { text: 'Troubleshooting', link: '/guide/troubleshooting' },
        { text: 'Contributing', link: '/guide/contributing' },
        { text: 'Changelog', link: '/reference/changelog' },
      ],
    },
  ];
}

function sidebarZh() {
  return [
    {
      text: '入门',
      collapsed: false,
      items: [
        { text: 'yondermesh 是什么？', link: '/zh/guide/what-is-yondermesh' },
        { text: '快速上手', link: '/zh/guide/quickstart' },
        { text: '安装', link: '/zh/guide/installation' },
      ],
    },
    {
      text: '概念',
      collapsed: false,
      items: [
        { text: '架构', link: '/zh/guide/architecture' },
        { text: 'Session 与拓扑', link: '/zh/guide/sessions' },
        { text: 'Daemon', link: '/zh/guide/daemon' },
        { text: '跨设备同步', link: '/zh/guide/sync' },
      ],
    },
    {
      text: '集成',
      collapsed: false,
      items: [
        { text: 'MCP Server', link: '/zh/guide/mcp' },
        { text: 'CLI 适配器', link: '/zh/reference/adapters' },
        { text: 'Skills 系统', link: '/zh/guide/skills' },
        { text: 'Mount 系统', link: '/zh/guide/mount' },
      ],
    },
    {
      text: '参考',
      collapsed: false,
      items: [
        { text: 'CLI 命令', link: '/zh/reference/cli' },
        { text: '配置文件', link: '/zh/reference/config' },
        { text: 'MCP 工具', link: '/zh/reference/mcp-tools' },
        { text: '文件布局', link: '/zh/reference/files' },
      ],
    },
    {
      text: '项目',
      collapsed: false,
      items: [
        { text: '常见问题', link: '/zh/guide/faq' },
        { text: '故障排查', link: '/zh/guide/troubleshooting' },
        { text: '贡献指南', link: '/zh/guide/contributing' },
        { text: '更新日志', link: '/zh/reference/changelog' },
      ],
    },
  ];
}
